version: '3.9'
services:
  backend:
    container_name: backend
    build:
      dockerfile: backend/Dockerfile
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:80'
    volumes:
      - ./backend:/src
    env_file:
      - .env.production
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.production
    volumes:
      # volume is mounted to the host machine /mnt/sdc
      - /mnt/sdc:/var/lib/postgresql/data

# attach volume: https://wiki.cybera.ca/display/RAC/Rapid+Access+Cloud+Guide%3A+Part+1#RapidAccessCloudGuide:Part1-Volumes
volumes:
  db:
    external: true
