# Generated by Django 4.0.5 on 2023-03-05 22:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('deadline', models.DateField()),
                ('link', models.URLField()),
                ('amount', models.IntegerField()),
                ('scholarship_picture', models.ImageField(blank=True, null=True, upload_to='scholarship_picture')),
                ('isApproved', models.CharField(choices=[('True', 'Approved'), ('False', 'Not Approved')], default=False, max_length=256)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_company', to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipTags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=255)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_tags', to='scholarships.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField(default='Hello, I want to apply for this scholarship.')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholar_applicant', to='app.regularuser')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='scholarships.scholarship')),
            ],
        ),
    ]
