# Generated by Django 4.0.5 on 2023-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
