# Generated by Django 4.0.5 on 2023-03-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_alter_scholarship_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': 'Scholarship', 'verbose_name_plural': 'Scholarships'},
        ),
        migrations.AlterModelOptions(
            name='scholarshipapplication',
            options={'verbose_name': 'Scholarship Application', 'verbose_name_plural': 'Scholarship Applications'},
        ),
        migrations.AlterModelOptions(
            name='scholarshiptags',
            options={'verbose_name': 'Scholarship Tag', 'verbose_name_plural': 'Scholarship Tags'},
        ),
    ]
