# Generated by Django 4.0.5 on 2023-03-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_companyapplication_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyapplication',
            options={'verbose_name': 'Company Application Request', 'verbose_name_plural': 'Company Application Requests'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='connecttocompany',
            options={'verbose_name': 'Company Connection Request', 'verbose_name_plural': 'Company Connection Requests'},
        ),
    ]
