# Generated by Django 4.0.5 on 2023-03-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('company', '0001_initial'),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_applicant', to='app.regularuser'),
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_company', to='company.companyprofile'),
        ),
    ]
