# Generated by Django 4.0.5 on 2023-03-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityapplication',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
