# Generated by Django 4.0.5 on 2023-03-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityapplication_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
