# Generated by Django 4.0.5 on 2023-03-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activityapplication',
            options={'verbose_name': 'Activity Application', 'verbose_name_plural': 'Activity Applications'},
        ),
        migrations.AlterModelOptions(
            name='activitytags',
            options={'verbose_name': 'Activity Tag', 'verbose_name_plural': 'Activity Tags'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Test Question', 'verbose_name_plural': 'Test Questions'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='useranswers',
            options={'verbose_name': 'Test Answer', 'verbose_name_plural': 'Test Answers'},
        ),
    ]
