# Generated by Django 4.0.5 on 2023-03-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityapplication',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='opportunity_picture',
            field=models.ImageField(blank=True, null=True, upload_to='activity_picture'),
        ),
    ]
