# Generated by Django 4.0.5 on 2023-03-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_alter_opportunity_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='job_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='job_skills',
            new_name='skills',
        ),
    ]
