# Generated by Django 4.0.5 on 2023-03-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0010_alter_connectwithmentee_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectwithmentee',
            options={'verbose_name': 'Mentor Connection Request', 'verbose_name_plural': 'Mentor Connection Requests'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentors'},
        ),
    ]
