# Generated by Django 4.0.5 on 2023-03-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0011_alter_connectwithmentee_options_alter_mentor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectwithmentee',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending')], max_length=8),
        ),
    ]
