# Generated by Django 4.0.5 on 2023-03-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_connecttomentor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecttomentor',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending')], max_length=8),
        ),
    ]
