# Generated by Django 4.0.5 on 2023-03-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_connecttomentor_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connecttomentor',
            options={'verbose_name': 'Mentor Connection Request', 'verbose_name_plural': 'Mentor Connection Requests'},
        ),
        migrations.AlterModelOptions(
            name='regularuser',
            options={'verbose_name': 'Regular User', 'verbose_name_plural': 'Regular Users'},
        ),
        migrations.AlterModelOptions(
            name='requesttobementor',
            options={'verbose_name': 'Mentor Application Request', 'verbose_name_plural': 'Mentor Application Requests'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'All Users'},
        ),
    ]
